/**
 * GET  /api/admin/production/transfer-suggestions
 *   List transfer suggestions, optionally filtered by status.
 *   Query params:
 *     status  – "pending" | "executed" | "dismissed" | "all"  (default: "pending")
 *     refresh – "true" triggers the suggestion algorithm before returning
 *
 * POST is intentionally not exposed here; suggestions are generated by the
 * algorithm only (called via ?refresh=true on GET, or by a scheduled job).
 */

import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/db/prisma'
import { withAdminAuth } from '@/lib/auth-middleware'
import { suggestTransfers } from '@/lib/transfer-suggester'

const VALID_STATUSES = ['pending', 'executed', 'dismissed'] as const
type SuggestionStatus = (typeof VALID_STATUSES)[number]

export const GET = withAdminAuth(async (req: NextRequest) => {
  try {
    const { searchParams } = new URL(req.url)

    // ------------------------------------------------------------------
    // 1. Parse query parameters
    // ------------------------------------------------------------------
    const statusParam = searchParams.get('status') ?? 'pending'
    const refresh = searchParams.get('refresh') === 'true'

    const statusFilter: SuggestionStatus[] =
      statusParam === 'all'
        ? [...VALID_STATUSES]
        : VALID_STATUSES.includes(statusParam as SuggestionStatus)
          ? [statusParam as SuggestionStatus]
          : ['pending']

    // ------------------------------------------------------------------
    // 2. Optionally refresh suggestions before querying
    // ------------------------------------------------------------------
    let refreshMeta: { created: number } | undefined
    if (refresh) {
      const result = await suggestTransfers()
      refreshMeta = { created: result.created }
    }

    // ------------------------------------------------------------------
    // 3. Fetch suggestions with related entities
    // ------------------------------------------------------------------
    const suggestions = await prisma.transferSuggestion.findMany({
      where: { status: { in: statusFilter } },
      include: {
        sourceLab: { select: { id: true, name: true } },
        destLab: { select: { id: true, name: true } },
        material: { select: { id: true, name: true, unit: true } },
      },
      orderBy: { createdAt: 'desc' },
    })

    return NextResponse.json({
      success: true,
      data: suggestions,
      ...(refreshMeta !== undefined ? { meta: { refreshed: true, newSuggestions: refreshMeta.created } } : {}),
    })
  } catch (err) {
    console.error('[transfer-suggestions] GET error:', err)
    return NextResponse.json(
      {
        success: false,
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An unexpected error occurred while fetching transfer suggestions.',
        },
      },
      { status: 500 },
    )
  }
})
