-- Migration: add_workflow_system
-- Date: 2026-04-19
-- Description: Phase 3 — Workflow automation system.
--   Replaces the placeholder workflow tables (Workflow, WorkflowStep,
--   WorkflowCondition, WorkflowAction, WorkflowExecution) and their enums
--   that were scaffolded in earlier migrations with the canonical Phase 3
--   design:
--
--     Workflow            – named automation rule created by an admin
--     WorkflowStep        – ordered node inside a workflow (ACTION or CONDITION)
--     WorkflowCondition   – boolean guard attached to a CONDITION step
--     WorkflowAction      – execution-history record for one step execution
--
--   The previous enums WorkflowTriggerType, WorkflowActionType, and
--   WorkflowConditionOperator are dropped and re-created with the
--   Phase 3 value sets.  WorkflowExecution is also removed; its role is
--   now covered by the WorkflowAction history table.

-- ============================================================================
-- STEP 1: DROP OLD WORKFLOW OBJECTS (reverse dependency order)
-- ============================================================================

-- Old WorkflowAction (step-config, not history) references WorkflowStep
DROP TABLE IF EXISTS "WorkflowAction"   CASCADE;
-- Old WorkflowCondition references WorkflowStep
DROP TABLE IF EXISTS "WorkflowCondition" CASCADE;
-- Old WorkflowExecution references Workflow
DROP TABLE IF EXISTS "WorkflowExecution" CASCADE;
-- Old WorkflowStep references Workflow
DROP TABLE IF EXISTS "WorkflowStep"     CASCADE;
-- Old Workflow root table
DROP TABLE IF EXISTS "Workflow"         CASCADE;

-- Drop old enum types (must happen after tables that reference them are gone)
DROP TYPE IF EXISTS "WorkflowTriggerType";
DROP TYPE IF EXISTS "WorkflowActionType";
DROP TYPE IF EXISTS "WorkflowConditionOperator";

-- ============================================================================
-- STEP 2: CREATE NEW ENUMS
-- ============================================================================

-- Trigger mechanism for a Workflow.
--   MANUAL       – executed on explicit admin request (Phase 3 default)
--   SCHEDULED    – executed on a cron schedule (Phase 4)
--   EVENT_BASED  – triggered by a system event such as low stock (Phase 4)
CREATE TYPE "WorkflowTriggerType" AS ENUM (
  'MANUAL',
  'SCHEDULED',
  'EVENT_BASED'
);

-- The kind of node a WorkflowStep represents.
--   ACTION    – executes a side-effect (transfer, notify, email, …)
--   CONDITION – evaluates one or more WorkflowConditions and branches
CREATE TYPE "WorkflowStepType" AS ENUM (
  'ACTION',
  'CONDITION'
);

-- Comparison operator used inside a WorkflowCondition.
--   EQUALS        – exact equality
--   GREATER_THAN  – numeric or string greater-than
--   LESS_THAN     – numeric or string less-than
--   CONTAINS      – substring / array membership check
CREATE TYPE "WorkflowConditionOperator" AS ENUM (
  'EQUALS',
  'GREATER_THAN',
  'LESS_THAN',
  'CONTAINS'
);

-- Lifecycle status of a single WorkflowAction execution record.
--   PENDING     – queued, not yet started
--   IN_PROGRESS – currently executing
--   COMPLETED   – finished successfully
--   FAILED      – finished with an error
CREATE TYPE "WorkflowActionStatus" AS ENUM (
  'PENDING',
  'IN_PROGRESS',
  'COMPLETED',
  'FAILED'
);

-- ============================================================================
-- STEP 3: CREATE NEW TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Workflow — a named, admin-created automation rule
-- ----------------------------------------------------------------------------
-- Each workflow has an ordered list of WorkflowSteps and an audit trail of
-- WorkflowAction execution records.  createdBy stores the admin user ID as a
-- plain TEXT value (no FK – User table structure is out of scope here).
CREATE TABLE "Workflow" (
    -- Primary key: CUID generated by the application layer
    "id"          TEXT        NOT NULL,

    -- Human-readable name, e.g. "Auto-transfer on low stock"
    "name"        TEXT        NOT NULL,

    -- Optional long-form description for admin UI tooltips
    "description" TEXT,

    -- Whether this workflow is available for execution
    "isActive"    BOOLEAN     NOT NULL DEFAULT true,

    -- How the workflow is triggered; defaults to MANUAL for Phase 3
    "triggerType" "WorkflowTriggerType" NOT NULL DEFAULT 'MANUAL',

    -- Admin user ID who created this workflow (no FK constraint)
    "createdBy"   TEXT        NOT NULL,

    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"   TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Workflow_pkey" PRIMARY KEY ("id")
);

-- Fast filtering of active/inactive workflows in the admin dashboard
CREATE INDEX "Workflow_isActive_idx" ON "Workflow"("isActive");

-- ----------------------------------------------------------------------------
-- WorkflowStep — one ordered node (ACTION or CONDITION) within a workflow
-- ----------------------------------------------------------------------------
-- stepNumber is the canonical 1-based execution order and is unique per
-- workflow.  The separate "order" column mirrors stepNumber so the API can
-- use either name without renaming.  Both are stored to keep the schema
-- self-documenting.
CREATE TABLE "WorkflowStep" (
    "id"            TEXT        NOT NULL,

    -- Parent workflow; cascade delete ensures no orphaned steps
    "workflowId"    TEXT        NOT NULL,

    -- 1-based execution order, unique within a workflow
    "stepNumber"    INTEGER     NOT NULL,

    -- ACTION executes a side-effect; CONDITION evaluates guards
    "type"          "WorkflowStepType" NOT NULL,

    -- Identifies the concrete action handler, e.g. "TRANSFER",
    -- "UPDATE_INVENTORY", "NOTIFY", "EMAIL".  NULL for CONDITION steps.
    "actionType"    TEXT,

    -- Flexible JSON payload for action configuration, e.g.:
    --   { "sourceLabId": "…", "destLabId": "…", "materialId": "…", "quantity": 100 }
    -- NULL for CONDITION steps.
    "actionPayload" JSONB,

    -- Mirrors stepNumber; provided for API ergonomics
    "order"         INTEGER     NOT NULL,

    "createdAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"     TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WorkflowStep_pkey" PRIMARY KEY ("id"),

    -- Prevent two steps from sharing the same stepNumber inside one workflow
    CONSTRAINT "WorkflowStep_workflowId_stepNumber_key" UNIQUE ("workflowId", "stepNumber"),

    CONSTRAINT "WorkflowStep_workflowId_fkey"
        FOREIGN KEY ("workflowId") REFERENCES "Workflow"("id")
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Fetch all steps for a given workflow
CREATE INDEX "WorkflowStep_workflowId_idx"            ON "WorkflowStep"("workflowId");

-- Fetch a specific step by workflow + position (covers ORDER BY stepNumber queries)
CREATE INDEX "WorkflowStep_workflowId_stepNumber_idx" ON "WorkflowStep"("workflowId", "stepNumber");

-- ----------------------------------------------------------------------------
-- WorkflowCondition — a boolean guard attached to a CONDITION step
-- ----------------------------------------------------------------------------
-- Multiple conditions on the same step are OR'd together.  Conditions across
-- different steps are AND'd (each step must pass before execution continues).
-- The "value" is always stored as TEXT and parsed at runtime.
CREATE TABLE "WorkflowCondition" (
    "id"        TEXT        NOT NULL,

    -- Parent step; cascade delete cleans up when a step is removed
    "stepId"    TEXT        NOT NULL,

    -- The field path to evaluate, e.g. "labStock.quantity", "materialId"
    "field"     TEXT        NOT NULL,

    -- Comparison operator applied between "field" and "value"
    "operator"  "WorkflowConditionOperator" NOT NULL,

    -- Comparison value stored as a string; parsed at runtime
    "value"     TEXT        NOT NULL,

    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WorkflowCondition_pkey" PRIMARY KEY ("id"),

    CONSTRAINT "WorkflowCondition_stepId_fkey"
        FOREIGN KEY ("stepId") REFERENCES "WorkflowStep"("id")
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Fetch all conditions for a given step
CREATE INDEX "WorkflowCondition_stepId_idx" ON "WorkflowCondition"("stepId");

-- ----------------------------------------------------------------------------
-- WorkflowAction — execution history record for one step run
-- ----------------------------------------------------------------------------
-- This table is an immutable audit log, NOT the action template (which lives
-- in WorkflowStep.actionType + actionPayload).  One row is inserted each time
-- a step is executed, capturing the outcome and any result/error payload.
CREATE TABLE "WorkflowAction" (
    "id"           TEXT        NOT NULL,

    -- Parent workflow (denormalised for efficient per-workflow history queries)
    "workflowId"   TEXT        NOT NULL,

    -- The step that was executed
    "stepId"       TEXT        NOT NULL,

    -- Lifecycle status of this execution attempt
    "status"       "WorkflowActionStatus" NOT NULL DEFAULT 'PENDING',

    -- Timestamp when the action reached COMPLETED or FAILED; NULL while pending
    "executedAt"   TIMESTAMP(3),

    -- JSON result payload, e.g.:
    --   { "transferredQuantity": 100, "sourceStock": 50, "destStock": 250 }
    "result"       JSONB,

    -- Human-readable error description when status = 'FAILED'
    "errorMessage" TEXT,

    "createdAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"    TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WorkflowAction_pkey" PRIMARY KEY ("id"),

    CONSTRAINT "WorkflowAction_workflowId_fkey"
        FOREIGN KEY ("workflowId") REFERENCES "Workflow"("id")
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT "WorkflowAction_stepId_fkey"
        FOREIGN KEY ("stepId") REFERENCES "WorkflowStep"("id")
        ON DELETE CASCADE ON UPDATE CASCADE
);

-- Filter execution history by workflow
CREATE INDEX "WorkflowAction_workflowId_idx" ON "WorkflowAction"("workflowId");

-- Filter execution history by step
CREATE INDEX "WorkflowAction_stepId_idx"     ON "WorkflowAction"("stepId");

-- Filter execution history by status (e.g. list all FAILED records)
CREATE INDEX "WorkflowAction_status_idx"     ON "WorkflowAction"("status");

-- List pending/failed records for a specific workflow (critical for Phase 3 API)
CREATE INDEX "WorkflowAction_workflowId_status_idx" ON "WorkflowAction"("workflowId", "status");
